### ISSUE TITLE
RuboCop Rails cops not working when different config location is used

### ISSUE THREAD

**Issue by Splines** [MaMpf-HD/mampf#768]
We don't use the default location of the RuboCop config file: `.rubocop.yml`. Instead, we place it inside `.config/.rubocop.yml` and specify the config flag via `--config .config/.rubocop.yml`. However, in the latter case, RuboCop does not seem to acknowledge the Rails routes, e.g. compare

```txt
# .rubocop.yml
775 files inspected, 3 offenses detected, 3 offenses autocorrectable

# ./.config/.rubocop.yml
775 files inspected, 141 offenses detected, 5 offenses autocorrectable
```

Note that for the latter, I adjusted the `Style/MethodCallWithArgsParentheses` `Exclude` pattern:

```yml
# .rubocop.yml
Exclude: ["../db/**/*"]

# ./.config/.rubocop.yml
Exclude: ["db/**/*"]
```
